### ISSUE TITLE
RFC:'Operate As' improvement

### ISSUE THREAD

**Issue by dellabiancial** [rspace-os/rspace-web#104] opened 2024-09-03 09:23 UTC
# Feature Request

As SysAdmin use the 'Operate As' feature only for 'WRITE' purposes inside the user. For browsing content purposes it would be really handy to be able to just click on the username to see the user profile and data.

**Comment by tilorspace** [comment] 2024-09-26 11:53
closing as duplicate of https://github.com/rspace-os/rspace-web/issues/131

**Closed** 2024-10-01 11:26 UTC
Labels: enhancement
